// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwaoLeHambBSYcBCw7iMbkH8I_yjL2-XE',
    appId: '1:834167435213:web:c17ecf654856a2c5975e84',
    messagingSenderId: '834167435213',
    projectId: 'esas-7d76f',
    authDomain: 'esas-7d76f.firebaseapp.com',
    storageBucket: 'esas-7d76f.firebasestorage.app',
    measurementId: 'G-BSH6JW4HEF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX4fG04ecuN-2HtHncpd3EpH7cRGu9fMQ',
    appId: '1:732843162485:android:0bf16c8ea889fe7617f13c',
    messagingSenderId: '732843162485',
    projectId: 'esas-90b5a',
    storageBucket: 'esas-90b5a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTT3AOf6D_NWd1M13ILEUtLJBPe8mtEDQ',
    appId: '1:732843162485:ios:e469638f1fb0b3e517f13c',
    messagingSenderId: '732843162485',
    projectId: 'esas-90b5a',
    storageBucket: 'esas-90b5a.firebasestorage.app',
    iosBundleId: 'com.example.esas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1FsQNASYDQKuDD-1Pbog-2qKDz9w8Ltk',
    appId: '1:834167435213:ios:f10b3e5dcf994d2c975e84',
    messagingSenderId: '834167435213',
    projectId: 'esas-7d76f',
    storageBucket: 'esas-7d76f.firebasestorage.app',
    iosBundleId: 'com.example.esasFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwaoLeHambBSYcBCw7iMbkH8I_yjL2-XE',
    appId: '1:834167435213:web:fd769b7a61a994ad975e84',
    messagingSenderId: '834167435213',
    projectId: 'esas-7d76f',
    authDomain: 'esas-7d76f.firebaseapp.com',
    storageBucket: 'esas-7d76f.firebasestorage.app',
    measurementId: 'G-2HTWLTD68P',
  );
}